# Funding and Sponsorship Options

# GitHub Sponsors (when available)
# github: cleargeo

# Open Collective
# open_collective: clearview-geographic

# Custom sponsorship/support links
custom:
  - "https://clearviewgeographic.com/enterprise"
  - "https://clearviewgeographic.com/pricing"
